flowchart LR
    K1["Keyframe 1<br/><code>duration: 0</code><br/><b>t = 0s</b>"]
    K2["Keyframe 2<br/><code>duration: 1</code><br/><b>t = 1s</b>"]
    K3["Keyframe 3<br/><code>duration: 2</code><br/><b>t = 3s</b>"]

    K1 -->|"1s of travel"| K2
    K2 -->|"2s of travel"| K3
